"""empty message

Revision ID: 59ab16c4edc2
Revises: fcefe4f38dcd
Create Date: 2026-03-02 17:04:51.172200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59ab16c4edc2'
down_revision = 'fcefe4f38dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.drop_column('focus_keyword')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_keyword', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
