"""Add post likes relationship

Revision ID: fcefe4f38dcd
Revises: aef17f3dfa0d
Create Date: 2026-03-02 15:53:01.704747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcefe4f38dcd'
down_revision = 'aef17f3dfa0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    op.drop_table('post_likes')
    # ### end Alembic commands ###
